application: appid
version: 1
runtime: python
api_version: 1

handlers:
- url: /(?:fetch|gaeproxy)\.(?:php|py)
  script: gaeproxy.py

- url: /(?:fetch0|forold)\.(?:php|py)
  script: forold.py

- url: /(?:fetch1|goagent)\.(?:php|py)
  script: goagent.py

- url: /(?:fetch2|simple)\.(?:php|py)
  script: simple.py
